[web]
vm0 ansible_host=20.109.108.221 ansible_user=azureuser ansible_ssh_private_key_file=/mnt/c/Users/men_l/Downloads/terraform-ansible/ssh.pem
vm1 ansible_host=20.97.231.255 ansible_user=azureuser ansible_ssh_private_key_file=/mnt/c/Users/men_l/Downloads/terraform-ansible/ssh.pem
