- hosts: kube_control_plane
  become: yes
  tasks:

    - name: Initialize control plane
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory
      file:
        path: /home/azureuser/.kube
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0700'

    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/azureuser/.kube/config
        owner: azureuser
        group: azureuser
        mode: '0600'
        remote_src: true

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Save join command
      copy:
        dest: /tmp/kubeadm_join.sh
        content: "{{ join_cmd.stdout }}"
        mode: '0755'
