apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: default
spec:
  serviceAccountName: test-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command: ["sleep", "20000"]
    resources:
      requests:
        cpu: "20m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
