apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.0.0.10
