# -----------------------------
# Grafana
# -----------------------------
grafana:
  enabled: true

  adminPassword: "admin123"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls: []

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: default

  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
      kubernetes-nodes:
        gnetId: 12156
        revision: 1
        datasource: Prometheus
      kubernetes-pods:
        gnetId: 6418
        revision: 1
        datasource: Prometheus

  grafana.ini:
    auth:
      disable_login_form: false

    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      client_id: grafana
      client_secret: "AQpy52CDKxdgci1QWjueVlQ7XDOctkFG"
      scopes: openid email profile

      auth_url:  http://localhost:8080/auth/realms/grafana/protocol/openid-connect/auth
      token_url: http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/grafana/protocol/openid-connect/token
      api_url:   http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/grafana/protocol/openid-connect/userinfo
      role_attribute_path: "contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'"      
      login_attribute_path: preferred_username
      name_attribute_path: name
      email_attribute_path: email
